# Generated by Django 5.1.15 on 2026-08-12 01:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('VRS_Digest', models.TextField(primary_key=True, serialize=False)),
                ('Gene_Symbol', models.TextField(db_index=True)),
                ('Reference_Sequence', models.TextField()),
                ('HGVS_cDNA', models.TextField(db_index=True)),
                ('BIC_Nomenclature', models.TextField()),
                ('HGVS_Protein', models.TextField()),
                ('Protein_Change', models.TextField()),
                ('CA_ID', models.TextField(db_index=True, null=True)),
                ('VRS', models.JSONField(blank=True, null=True)),
                ('Synonyms', models.TextField()),
                ('title', models.TextField(default='-')),
                ('ensembl_cdna', models.TextField(default='-')),
                ('ensembl_protein', models.TextField(default='-')),
            ],
            options={
                'db_table': 'variant',
            },
        ),
        migrations.CreateModel(
            name='DataRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.TextField()),
                ('archive', models.TextField()),
                ('date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('sources', models.TextField()),
                ('md5sum', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'data_release',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EnigmaDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.TextField()),
                ('name', models.TextField()),
                ('chrom', models.TextField()),
                ('assembly', models.TextField(default='GRCh38')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
            options={
                'db_table': 'data_enigma_domain',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PMID', models.TextField(db_index=True)),
                ('Title', models.TextField()),
                ('Author', models.TextField()),
                ('Year', models.TextField()),
                ('Journal', models.TextField()),
                ('DOI', models.TextField()),
            ],
            options={
                'db_table': 'data_paper',
            },
        ),
        migrations.CreateModel(
            name='AnalysisBayesDel',
            fields=[
                ('VRS_Digest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bayesdel_analysis', serialize=False, to='data.variant', db_column='VRS_Digest')),
                ('BayesDel_nsfp33a_noAF', models.TextField(null=True)),
                ('VA_Spec', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_bayesdel',
            },
        ),
        migrations.CreateModel(
            name='AnalysisPriors',
            fields=[
                ('VRS_Digest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='priors_analysis', serialize=False, to='data.variant', db_column='VRS_Digest')),
                ('varLoc', models.TextField(null=True)),
                ('applicablePrior', models.TextField(null=True)),
                ('proteinPrior', models.TextField(null=True)),
                ('refDonorPrior', models.TextField(null=True)),
                ('refRefDonorMES', models.TextField(null=True)),
                ('refRefDonorZ', models.TextField(null=True)),
                ('altRefDonorMES', models.TextField(null=True)),
                ('altRefDonorZ', models.TextField(null=True)),
                ('refRefDonorSeq', models.TextField(null=True)),
                ('altRefDonorSeq', models.TextField(null=True)),
                ('deNovoDonorPrior', models.TextField(null=True)),
                ('refDeNovoDonorMES', models.TextField(null=True)),
                ('refDeNovoDonorZ', models.TextField(null=True)),
                ('altDeNovoDonorMES', models.TextField(null=True)),
                ('altDeNovoDonorZ', models.TextField(null=True)),
                ('refDeNovoDonorSeq', models.TextField(null=True)),
                ('altDeNovoDonorSeq', models.TextField(null=True)),
                ('deNovoDonorGenomicSplicePos', models.TextField(null=True)),
                ('deNovoDonorTranscriptSplicePos', models.TextField(null=True)),
                ('closestDonorGenomicSplicePos', models.TextField(null=True)),
                ('closestDonorTranscriptSplicePos', models.TextField(null=True)),
                ('closestDonorRefMES', models.TextField(null=True)),
                ('closestDonorRefZ', models.TextField(null=True)),
                ('closestDonorRefSeq', models.TextField(null=True)),
                ('closestDonorAltMES', models.TextField(null=True)),
                ('closestDonorAltZ', models.TextField(null=True)),
                ('closestDonorAltSeq', models.TextField(null=True)),
                ('refAccPrior', models.TextField(null=True)),
                ('refRefAccMES', models.TextField(null=True)),
                ('refRefAccZ', models.TextField(null=True)),
                ('altRefAccMES', models.TextField(null=True)),
                ('altRefAccZ', models.TextField(null=True)),
                ('refRefAccSeq', models.TextField(null=True)),
                ('altRefAccSeq', models.TextField(null=True)),
                ('VA_Spec', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_priors',
            },
        ),
        migrations.CreateModel(
            name='AnalysisSpliceAI',
            fields=[
                ('VRS_Digest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='spliceai_analysis', serialize=False, to='data.variant', db_column='VRS_Digest')),
                ('DS_AG', models.TextField(null=True)),
                ('DS_AL', models.TextField(null=True)),
                ('DS_DG', models.TextField(null=True)),
                ('DS_DL', models.TextField(null=True)),
                ('DP_AG', models.TextField(null=True)),
                ('DP_AL', models.TextField(null=True)),
                ('DP_DG', models.TextField(null=True)),
                ('DP_DL', models.TextField(null=True)),
                ('result', models.TextField(null=True)),
                ('VA_Spec', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_spliceai',
            },
        ),
        migrations.CreateModel(
            name='AnalysisVEP',
            fields=[
                ('VRS_Digest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vep_analysis', serialize=False, to='data.variant', db_column='VRS_Digest')),
                ('variant_class', models.TextField(null=True)),
                ('variant_type', models.TextField(null=True)),
                ('VA_Spec', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_vep',
            },
        ),
        migrations.CreateModel(
            name='Variant_in_ClinVar',
            fields=[
                ('VRS_Digest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clinvar_data', serialize=False, to='data.variant', db_column='VRS_Digest')),
                ('Source_URL', models.TextField()),
            ],
            options={
                'db_table': 'variant_clinvar',
            },
        ),
        migrations.CreateModel(
            name='Variant_in_ExLOVD',
            fields=[
                ('VRS_Digest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='exlovd_data', serialize=False, to='data.variant', db_column='VRS_Digest')),
                ('Source_URL', models.TextField(null=True)),
                ('Exon', models.TextField(null=True)),
                ('DNA_Change', models.TextField(null=True)),
                ('BIC_DNA_Change', models.TextField(null=True)),
                ('Protein_Change', models.TextField(null=True)),
                ('DBID', models.TextField(null=True)),
                ('Posterior_P', models.TextField(default='-', null=True)),
                ('IARC_Class', models.TextField(default='-', null=True)),
                ('Missense_Analysis_Prior_P', models.TextField(default='-', null=True)),
                ('Combined_Prior_P', models.TextField(default='-', null=True)),
                ('Segregation_LR', models.TextField(default='-', null=True)),
                ('Splicing_Prior_P', models.TextField(null=True)),
                ('Pathology_LR', models.TextField(null=True)),
                ('Co_Occurrence_LR', models.TextField(default='-', null=True)),
                ('Case_Control_LR', models.TextField(null=True)),
                ('Product_Of_LRs', models.TextField(null=True)),
                ('Comments', models.TextField(default='-', null=True)),
            ],
            options={
                'db_table': 'variant_exlovd',
            },
        ),
        migrations.CreateModel(
            name='Variant_in_GnomAD',
            fields=[
                ('VRS_Digest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gnomad_data', serialize=False, to='data.variant', db_column='VRS_Digest')),
                ('Source_URL', models.TextField(default='-', null=True)),
            ],
            options={
                'db_table': 'variant_gnomad',
            },
        ),
        migrations.CreateModel(
            name='Variant_in_LOVD',
            fields=[
                ('VRS_Digest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lovd_data', serialize=False, to='data.variant', db_column='VRS_Digest')),
                ('Source_URL', models.TextField()),
                ('Variant_haplotype', models.TextField()),
            ],
            options={
                'db_table': 'variant_lovd',
            },
        ),
        migrations.CreateModel(
            name='Variant_in_Other',
            fields=[
                ('VRS_Digest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='other_data', serialize=False, to='data.variant', db_column='VRS_Digest')),
                ('data_type', models.TextField(null=True)),
                ('variant_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'variant_other',
            },
        ),
        migrations.CreateModel(
            name='Variant_in_ENIGMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Condition_ID_type', models.TextField()),
                ('Condition_ID_value', models.TextField()),
                ('Condition_category', models.TextField()),
                ('Clinical_significance', models.TextField()),
                ('Date_last_evaluated', models.TextField()),
                ('Assertion_method', models.TextField()),
                ('Assertion_method_citation', models.TextField()),
                ('Clinical_significance_citations', models.TextField()),
                ('Comment_on_clinical_significance', models.TextField()),
                ('Collection_method', models.TextField()),
                ('Allele_origin', models.TextField()),
                ('ClinVarAccession', models.TextField()),
                ('Pathogenicity', models.TextField()),
                ('VRS_Digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enigma_reports', to='data.variant', db_column='VRS_Digest')),
            ],
            options={
                'db_table': 'variant_enigma',
            },
        ),
        migrations.CreateModel(
            name='Report_in_ClinVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clinical_Significance', models.TextField()),
                ('Date_Last_Updated', models.TextField()),
                ('DateSignificanceLastEvaluated', models.TextField(default='-')),
                ('Submitter', models.TextField()),
                ('SCV', models.TextField(db_index=True)),
                ('SCV_Version', models.TextField(default='-')),
                ('Allele_Origin', models.TextField()),
                ('Method', models.TextField()),
                ('Description', models.TextField(default='-')),
                ('Summary_Evidence', models.TextField(default='-')),
                ('Review_Status', models.TextField(default='-')),
                ('Condition_Type', models.TextField(default='-')),
                ('Condition_Value', models.TextField(default='-')),
                ('Condition_DB_ID', models.TextField(default='-')),
                ('VRS_Digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinvar_reports', to='data.variant_in_clinvar', db_column='VRS_Digest')),
            ],
            options={
                'db_table': 'report_clinvar',
            },
        ),
        migrations.CreateModel(
            name='Report_in_LOVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Variant_frequency', models.TextField()),
                ('Individuals', models.TextField()),
                ('Variant_effect', models.TextField()),
                ('Genetic_origin', models.TextField()),
                ('Submitters', models.TextField()),
                ('Functional_analysis_technique', models.TextField(default='-')),
                ('Functional_analysis_result', models.TextField(default='-')),
                ('Created_date', models.TextField(default='-')),
                ('Edited_date', models.TextField(default='-')),
                ('DBID', models.TextField(default='-')),
                ('Remarks', models.TextField(null=True)),
                ('Classification', models.TextField(null=True)),
                ('Submission_ID', models.TextField(db_index=True, default='-')),
                ('VRS_Digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lovd_reports', to='data.variant_in_lovd', db_column='VRS_Digest')),
            ],
            options={
                'db_table': 'report_lovd',
            },
        ),
        migrations.CreateModel(
            name='AnalysisProvisionalEvidenceCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popfreq_code', models.TextField(null=True)),
                ('popfreq_description', models.TextField(null=True)),
                ('method_name', models.TextField()),
                ('gnomad_version', models.TextField(null=True)),
                ('gnomad_data_type', models.TextField(null=True)),
                ('VA_Spec', models.JSONField(blank=True, null=True)),
                ('VRS_Digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisional_evidence_codes', to='data.variant', db_column='VRS_Digest')),
            ],
            options={
                'db_table': 'analysis_provisional_evidence_codes',
                'unique_together': {('VRS_Digest', 'method_name')},
            },
        ),
        migrations.CreateModel(
            name='Genomic_Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly', models.TextField()),
                ('hgvs', models.TextField()),
                ('chr', models.TextField()),
                ('pos', models.TextField()),
                ('end_pos', models.TextField()),
                ('ref', models.TextField()),
                ('alt', models.TextField()),
                ('VRS_Digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genomic_coordinates', to='data.variant', db_column='VRS_Digest')),
            ],
            options={
                'db_table': 'variant_genomic_coordinates',
                'unique_together': {('VRS_Digest', 'assembly')},
            },
        ),
        migrations.CreateModel(
            name='Variant_in_Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('variant_mentioned_as', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('Paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.paper')),
                ('VRS_Digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.variant', db_column='VRS_Digest')),
            ],
            options={
                'db_table': 'data_variantpaper',
                'unique_together': {('VRS_Digest', 'Paper')},
            },
        ),
        migrations.CreateModel(
            name='Report_in_GnomAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.TextField(null=True)),
                ('data_type', models.TextField(default='-')),
                ('Variant_id', models.TextField(db_index=True, default='-', null=True)),
                ('Flags', models.TextField(default='-', null=True)),
                ('coverage', models.TextField(default='-')),
                ('Allele_count', models.TextField(default='-', null=True)),
                ('Allele_number', models.TextField(default='-', null=True)),
                ('Allele_frequency', models.TextField(default='-', null=True)),
                ('faf95_popmax', models.TextField(default='-', null=True)),
                ('faf95_popmax_population', models.TextField(default='-', null=True)),
                ('populations', models.JSONField(blank=True, null=True)),
                ('VRS_Digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gnomad_reports', to='data.variant_in_gnomad', db_column='VRS_Digest')),
            ],
            options={
                'db_table': 'report_gnomad',
                'unique_together': {('VRS_Digest', 'version', 'data_type')},
            },
        ),
    ]
