# Generated by Django 5.1.15 on 2026-08-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisvep',
            name='consequences',
            field=models.TextField(null=True),
        ),
    ]
