# Generated by Django 5.1.15 on 2026-08-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_analysisvep_consequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisvep',
            name='hgvsp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='analysisvep',
            name='ptc_genomic_pos',
            field=models.IntegerField(null=True),
        ),
    ]
