# Generated by Django 5.2.13 on 2026-08-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_analysisvep_hgvsp_ptc_genomic_pos'),
    ]

    operations = [
        # 0001_initial creates data_release, but some schemas that have
        # 0001_initial applied (e.g. pipeline, vcep_development) don't have the
        # table.  Create it with 0001_initial's definition if it's missing, so
        # the AddFields below can run; where it already exists this is a no-op.
        # Reversing leaves the table alone, since it belongs to 0001_initial.
        migrations.RunSQL(
            sql='''
                CREATE TABLE IF NOT EXISTS "data_release" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "schema" text NOT NULL,
                    "archive" text NOT NULL,
                    "date" timestamp with time zone NOT NULL,
                    "notes" text NOT NULL,
                    "sources" text NOT NULL,
                    "md5sum" text NOT NULL,
                    "created" timestamp with time zone NULL,
                    "name" integer NOT NULL CHECK ("name" >= 0)
                );
            ''',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='datarelease',
            name='variants_added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datarelease',
            name='variants_classified',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datarelease',
            name='variants_deleted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datarelease',
            name='variants_modified',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
