# Generated by Django 5.2.13 on 2026-08-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_analysisvep_hgvsp_ptc_genomic_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarelease',
            name='variants_added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datarelease',
            name='variants_classified',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datarelease',
            name='variants_deleted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datarelease',
            name='variants_modified',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
