# Generated by Django 5.1.15 on 2026-09-08 01:45

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_analysisvep_hgvsp_ptc_genomic_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHerediClassify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provenance_metadata', models.JSONField()),
                ('method_name', models.GeneratedField(db_persist=True, expression=django.db.models.fields.json.KeyTextTransform('method_name', 'provenance_metadata'), output_field=models.TextField())),
                ('classification_protein', models.IntegerField(null=True)),
                ('classification_splicing', models.IntegerField(null=True)),
                ('rules', models.JSONField(blank=True, null=True)),
                ('VA_Spec', models.JSONField(blank=True, null=True)),
                ('VRS_Digest', models.ForeignKey(db_column='VRS_Digest', on_delete=django.db.models.deletion.CASCADE, related_name='herediclassify_results', to='data.variant')),
            ],
            options={
                'db_table': 'analysis_herediclassify',
                'indexes': [models.Index(fields=['classification_protein'], name='herediclassify_class_prot_idx'), django.contrib.postgres.indexes.GinIndex(fields=['rules'], name='herediclassify_rules_gin'), django.contrib.postgres.indexes.GinIndex(fields=['provenance_metadata'], name='herediclassify_prov_gin')],
                'unique_together': {('VRS_Digest', 'method_name')},
            },
        ),
    ]
