# Generated by Django 5.1.15 on 2026-09-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_add_release_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant_in_clinvar',
            name='Clinical_Significance',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='variant_in_clinvar',
            name='Condition_DB_IDs',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='variant_in_clinvar',
            name='Conditions',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='variant_in_clinvar',
            name='Date_Last_Evaluated',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='variant_in_clinvar',
            name='Date_Last_Updated',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='variant_in_clinvar',
            name='Explanation',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='variant_in_clinvar',
            name='Most_Recent_Submission',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='variant_in_clinvar',
            name='Number_Of_Submissions',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='variant_in_clinvar',
            name='Number_Of_Submitters',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='variant_in_clinvar',
            name='Review_Status',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='variant_in_clinvar',
            name='VCV_Accession',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='variant_in_clinvar',
            name='VCV_Version',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='variant_in_clinvar',
            name='Variation_ID',
            field=models.TextField(default='-'),
        ),
    ]
