# Generated by Django 5.1.15 on 2026-09-08 03:33

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_analysisherediclassify'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisAriane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provenance_metadata', models.JSONField()),
                ('method_name', models.GeneratedField(db_persist=True, expression=django.db.models.fields.json.KeyTextTransform('method_name', 'provenance_metadata'), output_field=models.TextField())),
                ('criteria', models.JSONField(blank=True, null=True)),
                ('result_detail', models.JSONField(blank=True, null=True)),
                ('VA_Spec', models.JSONField(blank=True, null=True)),
                ('VRS_Digest', models.ForeignKey(db_column='VRS_Digest', on_delete=django.db.models.deletion.CASCADE, related_name='ariane_results', to='data.variant')),
            ],
            options={
                'db_table': 'analysis_ariane',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['criteria'], name='ariane_criteria_gin'), django.contrib.postgres.indexes.GinIndex(fields=['result_detail'], name='ariane_detail_gin'), django.contrib.postgres.indexes.GinIndex(fields=['provenance_metadata'], name='ariane_prov_gin')],
                'unique_together': {('VRS_Digest', 'method_name')},
            },
        ),
    ]
