# Generated by Django 5.1.15 on 2026-09-11 19:25

import django.db.models.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_analysisariane'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisariane',
            name='ariane_version',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.fields.json.KeyTextTransform('ariane_version', 'provenance_metadata'), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='analysisariane',
            name='build_version',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.fields.json.KeyTextTransform('build_version', 'provenance_metadata'), output_field=models.TextField()),
        ),
        migrations.AddIndex(
            model_name='analysisariane',
            index=models.Index(fields=['ariane_version'], name='ariane_version_idx'),
        ),
    ]
